typography_spectrum: 0.40302811609581113
color:
  brandStrength: 0.45479696663096547
  lightness: 0.9422740992158651
  saturation: 0.08629970159381628
  rhythmicContrast: 0.040033788653090596
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.33395748981274664
name: Jiri Ospalik
navigation:
  - name: Facebook Pages
    url: 'https://www.facebook.com/pages/Jiri-Ospalik/174950935881613'
    type: external
  - name: Personal Pages
    url: 'http://jiriospalik.com/'
    type: external
  - name: Photos
    id: 0c7c6ca7-1f48-41ec-b399-085faab4b9f3
    type: content
title: Jiri Ospalik
