typography_spectrum: 0.40302811609581113
color:
  brandStrength: 0.45479696663096547
  lightness: 0.9422740992158651
  saturation: 0.08629970159381628
  rhythmicContrast: 0.040033788653090596
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  appId: 'https://www.facebook.com/jiriospalik/'
  type: Profile
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd97e12a-813b-4be4-abbf-ef88bc349e20.jpg
layout_spectrum: 0.33395748981274664
author:
  name: Jiri Ospalik
  email: jiri.ospalik@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e82d56e-a5a0-4c6c-9900-46e7bf957085.jpg
name: Jiri Ospalik
navigation:
  - name: Facebook Pages
    url: 'https://www.facebook.com/pages/Jiri-Ospalik/174950935881613'
    type: external
  - name: Personal Pages
    url: 'http://jiriospalik.com/'
    type: external
  - name: Photos
    id: 0c7c6ca7-1f48-41ec-b399-085faab4b9f3
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9f9cb204-7e74-4380-9b4e-357b67128fa9.jpg
title: Jiri Ospalik - Composer and Pianist
description: Composer and Pianist
